---
server:
    port: ${port:8080}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://iu51mf0q32fkhfpl.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/owag27zlnmn2ve2w
    username: lwkhap0puqy6cyeq
    password: bltz2sj4sfccpgb0
    hikari:
      maximum-pool-size: 5
      leakDetectionThreshold: 240000
      connection-test-query: SELECT 1 from dual
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml

# kakao auth info
oauth:
  kakao:
    infoUrl: https://kapi.kakao.com                   #
    baseUrl: https://kauth.kakao.com                  # 인가코드 요청 url
    clientId: 6e8e0e1b1c81cbfb29ac2e7cc2576b6e        # rest api key
    redirectId: https://localhost:3000/oauth/kakao    # token uri
    secretKey: a3lNifTx4xim2mKIUXbbjyuTbfoQM1YU       # admin key
