---
server:
    port: ${port:8080}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://iu51mf0q32fkhfpl.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/owag27zlnmn2ve2w
    username: lwkhap0puqy6cyeq
    password: bltz2sj4sfccpgb0
    hikari:
      maximum-pool-size: 5
      leakDetectionThreshold: 240000
      connection-test-query: SELECT 1 from dual
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml